<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="P5-GKZ5T72" name="Test-regression" tests="3" failures="1" timestamp="14 Jun 2019 06:00:15 GMT" time="0.119" errors="0">
  <testcase name="test1" time="0.045" classname="testngFeatures.DemoAssertion"/>
  <testcase name="test2" time="0.005" classname="testngFeatures.DemoAssertion">
    <failure type="java.lang.AssertionError" message="error msg 2 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: error msg 2 expected [true] but found [false]
	at testngFeatures.DemoAssertion.test2(DemoAssertion.java:18)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.003" classname="testngFeatures.DemoAssertion"/>
</testsuite> <!-- Test-regression -->
